version: '3.4'

services:
  static-web:
    image: nginx:1.13.8-alpine
    volumes:
      - type      : bind
        source    : ../static-web
        target    : /project
        read_only : true
      - type: bind
        source: ./conf/static-web-nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "127.0.0.1:10080:80"
